name: Build and Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            asset_name: portable-encryptor-windows.exe
          - os: macos-latest
            asset_name: portable-encryptor-macos
          - os: ubuntu-latest
            asset_name: portable-encryptor-linux
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install .
    - name: Build binary
      run: |
        # Debug: List files to make sure main.py exists
        ls -la
        pwd
        # Build the binary with explicit path
        pyinstaller --onefile --name ${{ matrix.asset_name }} ./main.py
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
